### ISSUE TITLE
clojure optimization

### ISSUE THREAD

**Issue by orlin** [simurai/duotone-light-syntax#1]
Please optimize for Clojure[Script] too!  This is my favorite light theme...

**Comment by simurai** [comment]
@orlin I'm not that familiar with Clojure. If you have some sample code that you could paste here, I can try to style it.

**Comment by simurai** [comment]
Also.. ping to https://github.com/varemenos/duotone-dusk-syntax/issues/1

**Comment by simurai** [comment]
Clojure support should be improved in #3.
